/**
 * Pure data helpers — no mock, no fetch.
 *
 * This file used to be the mock data layer: a seeded generator producing every DTO the site
 * rendered. All of that is gone. Real data comes from `api.js` now, and what remains here is the
 * set of pure, source-agnostic functions the components and `adapter.js` still use — match
 * derivations that reshape a match DTO into the trace/standings the charts want, item and identity
 * formatting, and the leaderboard metadata lists.
 *
 * These read the *real* DTO shapes. Where a match carries a player, that player is a nested
 * identity ({ playerUuid, playerName }), not a flat uuid — the same shape the plugin and the views
 * moved to. The helpers below were updated to read it.
 */

import { ITEM_TEXTURE_BASE, RARITY_KEYS, RARITY_FIELDS } from './tokens.js';

export { RARITY_KEYS, RARITY_FIELDS };

/*
 * The full item pool, regenerated by `npm run vendor:pool` from the plugin source.
 * Re-exported here because this is where it has always lived for its consumers
 * (the collection book, and vendor-textures.mjs' reachable set).
 */
export { ITEM_POOL, ITEM_STATE } from './itemPool.js';

// ── Identity ─────────────────────────────────────────────────────────────────
//
// There is no player table on the client any more — names arrive inside the DTOs (a match
// participant carries its FibPlayer, a leaderboard row carries its player). So these are pure
// fallbacks for the few places that hold only a uuid and no identity object: a short uuid stands in
// until the name is in scope. Prefer reading `someObject.player.playerName` directly wherever the
// DTO provides it; reach for playerName(uuid) only when it genuinely does not.

/** A display string for a bare uuid: the first eight characters. Real names come from the DTO. */
export const playerName = (uuid) => (uuid ? String(uuid).slice(0, 8) : 'Unknown');

/**
 * Read a player identity, tolerant of both field-namings.
 *
 * The public API serializes its FibPlayer as { uuid, name } — those are the getter names on the
 * server object, so those are the JSON keys the frontend actually receives. (The generated *client*
 * DTO calls them playerUuid/playerName, but that shape never reaches the browser; the public API
 * re-serializes through its own class.) These helpers read `uuid`/`name` first and fall back to the
 * nested names, so a payload of either shape resolves — and everything that shows a player goes
 * through here rather than reaching into the object, so there is one place this naming lives.
 */
export const idUuid = (identity) => identity?.uuid ?? identity?.playerUuid ?? null;
export const idName = (identity) => identity?.name ?? identity?.playerName ?? null;

/** A player identity's display name: the real name if recorded, else the short uuid, else Unknown. */
export const idLabel = (identity) => {
    const name = idName(identity);
    if (name) return name;
    const uuid = idUuid(identity);
    return uuid ? String(uuid).slice(0, 8) : 'Unknown';
};

/** A head-renderer URL for a uuid. The renderer keys on uuid, so this needs no name. */
export const playerAvatar = (uuid) => `https://mc-heads.net/avatar/${uuid ?? 'MHF_Question'}/48`;

// ── Items ───────────────────────────────────────────────────────────────────
// Stored namespaced ("minecraft:oak_log") so the data outlives MC version churn;
// everything user-facing strips it. Texture filenames drop the namespace.
//
// Lower-cased: item ids are canonically lowercase, but this API hands them back
// as SCREAMING_ENUMS ("CHIPPED_ANVIL"). Texture files — both the vendored set in
// public/fib-items and the remote pack — are lowercase, and a case-sensitive
// static server (Vite's dev server, and the production host) 404s the uppercase
// path, so every sprite fell through to the fallback and then to a broken image.
// Normalising here also un-breaks itemLabel's Title-casing, which only works on
// a lowercase base.
export const itemKey = (itemName) => (itemName || '').split(':').pop().toLowerCase();
export const itemLabel = (itemName) =>
    itemKey(itemName).split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
export const itemTexture = (itemName) => `${ITEM_TEXTURE_BASE}/${itemKey(itemName)}.png`;

// ── Leaderboard metadata ─────────────────────────────────────────────────────
// Presentation metadata for the boards: labels, number formats, and which direction is better.
// Not used to decide what to fetch — the valid category set lives server-side (FibLeaderboard
// category) and is deliberately not mirrored as a fetch gate; this only styles what comes back.

export const LEADERBOARD_SCOPES = [
    { id: 'solo', label: 'Solo' },
    { id: 'duo', label: 'Duo' },
    { id: 'combined', label: 'Teams' },
];

export const LEADERBOARD_CATEGORIES = [
    { id: 'GAMES_WON', label: 'Wins', format: 'number', sense: 'high' },
    { id: 'HIGHEST_SCORE', label: 'Top score', format: 'number', sense: 'high' },
    { id: 'TOTAL_ITEMS', label: 'Items', format: 'number', sense: 'high' },
    /* Spelled out. "B2B streak" is server shorthand sitting in a row of
       plain-English labels, and the profile calls the same number
       "Back-to-back best" three clicks away. */
    { id: 'BACK_TO_BACK_STREAK', label: 'Back-to-back', format: 'number', sense: 'high' },
    { id: 'BLOCKS_TRAVELLED', label: 'Distance', format: 'distance', sense: 'high' },
    { id: 'DEATHS', label: 'Deaths', format: 'number', sense: 'low' },
];

export const categorySense = (category) =>
    LEADERBOARD_CATEGORIES.find((c) => c.id === category)?.sense ?? 'high';

// ── Match derivations ────────────────────────────────────────────────────────
//
// These reshape a real match DTO (FibMatchDetail) into the standings and race entries the tables
// and charts consume. A match participant carries a nested `player` ({ playerUuid, playerName });
// a match item carries a nested `player` or a `teamIndex`. The `members` a standing exposes are
// therefore identity objects, not bare uuids, so a caller can render the name the DTO already
// carries instead of a lookup.

/** A uuid from a participant, reading the real { uuid, name } identity (or the nested variant). */
const uuidOf = (p) => idUuid(p?.player) ?? idUuid(p) ?? null;

/** A normalized identity { uuid, name } from a participant, for `members` lists. */
const identityOf = (p) => {
    const id = p?.player ?? p;
    return { uuid: idUuid(id), name: idName(id) };
};

/**
 * The real elapsed duration of a match, in seconds — from the start/end timestamps, NOT the stored
 * durationSeconds.
 *
 * durationSeconds cannot be trusted: it carries the configured round length (e.g. 3600 for a 60-min
 * round) even when the match actually ran longer, so a match that went 88 minutes still reports
 * 3600. startedAt and endedAt are real event timestamps and are authoritative. Everything that needs
 * a time axis or a "final" cutoff — the race graph, the replay scrubber, the at-rest standings —
 * uses this, so items collected past the nominal round length are not silently dropped.
 */
export const matchDuration = (match) => {
    const start = new Date(match.startedAt).getTime();
    const end = new Date(match.endedAt).getTime();
    const span = (end - start) / 1000;
    // Fall back to the stored field only if the timestamps are missing or nonsensical.
    return Number.isFinite(span) && span > 0 ? span : (match.durationSeconds ?? 0);
};

export const matchStandings = (match) => {
    if (match.mode === 'SOLO') {
        return match.participants
            .slice()
            .sort((a, b) => a.placement - b.placement)
            .map((p) => ({
                key: uuidOf(p),
                owner: { playerUuid: uuidOf(p), teamIndex: null },
                members: [identityOf(p)],
                placement: p.placement,
                score: p.finalScore,
                won: p.won,
            }));
    }
    return match.teams
        .map((team) => {
            const members = match.participants.filter((p) => p.teamIndex === team.teamIndex);
            const first = members[0];
            return {
                key: `t${team.teamIndex}`,
                owner: { playerUuid: null, teamIndex: team.teamIndex },
                members: members.map(identityOf),
                placement: first?.placement ?? 0,
                score: first?.finalScore ?? 0,
                won: first?.won ?? false,
            };
        })
        .sort((a, b) => a.placement - b.placement);
};

export const itemsForOwner = (match, owner) =>
    (match?.items ?? [])
        .filter((it) =>
            owner.teamIndex != null ? it.teamIndex === owner.teamIndex : uuidOf(it) === owner.playerUuid,
        )
        .sort((a, b) => a.orderIndex - b.orderIndex);

/**
 * Competitors reshaped for the trace: each event carries its offset in seconds from the match
 * start, which is all the chart and the strips need.
 */
export const raceEntries = (match) => {
    const start = new Date(match.startedAt).getTime();
    return matchStandings(match).map((row, i) => ({
        ...row,
        index: i,
        events: itemsForOwner(match, row.owner).map((it) => ({
            t: Math.max(0, (new Date(it.collectedAt).getTime() - start) / 1000),
            skipped: it.skipped,
            b2b: it.b2bRarity,
            itemName: it.itemName,
        })),
    }));
};

/** Score is item count including skips — skips score, which is why they count. */
export const scoreAt = (entry, t) => entry.events.filter((e) => e.t <= t).length;

export const eventTimes = (entries) =>
    [...new Set(entries.flatMap((e) => e.events.map((ev) => ev.t)))].sort((a, b) => a - b);

export const standingsAt = (entries, t) => {
    const rows = entries
        .map((entry) => {
            const seen = entry.events.filter((e) => e.t <= t);
            return {
                entry,
                score: seen.length,
                found: seen.filter((e) => !e.skipped).length,
                skipped: seen.filter((e) => e.skipped).length,
                b2b: seen.filter((e) => e.b2b).length,
            };
        })
        .sort((a, b) => b.score - a.score || a.entry.index - b.entry.index);
    const lead = rows[0]?.score ?? 0;
    return rows.map((r, i) => ({ ...r, pos: i + 1, gap: r.score - lead }));
};

export const leadChanges = (entries) => {
    let count = 0;
    let lead = null;
    for (const t of eventTimes(entries)) {
        const top = standingsAt(entries, t)[0]?.entry.index;
        if (lead != null && top !== lead) count++;
        lead = top;
    }
    return count;
};

/**
 * The moments the lead actually changed hands, as offsets in seconds.
 *
 * `leadChanges` counts these for a headline figure; the timeline underneath the race trace marks
 * them, because "when it turned" is the most useful landmark on the chart. Same walk, keeping the
 * timestamps.
 */
export const leadChangeTimes = (entries) => {
    const times = [];
    let lead = null;
    for (const t of eventTimes(entries)) {
        const top = standingsAt(entries, t)[0]?.entry.index;
        if (lead != null && top !== lead) times.push(t);
        lead = top;
    }
    return times;
};

/** Segments for the item strips: width is the time that item took. */
export const itemSegments = (entry) =>
    entry.events.map((e, i) => ({
        ...e,
        order: i + 1,
        took: e.t - (i ? entry.events[i - 1].t : 0),
    }));

// ── Number & time formatting ─────────────────────────────────────────────────
// Pure formatters used across the whole UI (and re-exported through format.js). No mock
// dependency — they format whatever value they are handed.

export const formatNumber = (n) => {
    if (n == null) return '—';
    if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M`;
    if (n >= 10000) return `${(n / 1000).toFixed(1)}K`;
    // Locale pinned: left to the browser, a German client renders "1.216.896" while every other
    // formatter says "1,216,896".
    return n.toLocaleString('en-US');
};

export const formatDistance = (b) => {
    if (b == null) return '—';
    if (b >= 1000000) return `${(b / 1000000).toFixed(2)}M`;
    if (b >= 1000) return `${(b / 1000).toFixed(1)}K`;
    return b.toLocaleString('en-US');
};

/** Clock form "42:07" — match durations, offsets, per-item times. */
export const mmss = (s) => {
    const total = Math.max(0, Math.round(s));
    if (total >= 3600) return `${Math.floor(total / 3600)}:${String(Math.floor((total % 3600) / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
    return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, '0')}`;
};

export const formatTime = (s) => {
    if (s == null || Number.isNaN(s)) return '—';
    const total = Math.round(s);
    if (total >= 60) return `${Math.floor(total / 60)}m ${total % 60}s`;
    return `${total}s`;
};

export const formatDate = (v) => {
    const d = new Date(v);
    const days = Math.floor((Date.now() - d.getTime()) / 86400000);
    if (days <= 0) return 'Today';
    if (days === 1) return 'Yesterday';
    if (days < 7) return `${days} days ago`;
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
};

export const formatClock = (v) => {
    const d = new Date(v);
    return Number.isNaN(d.getTime()) ? '—' : d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
};

export const formatByKind = (value, kind) => {
    if (kind === 'compact') return formatNumber(value);
    if (kind === 'distance') return `${formatDistance(value)} blocks`;
    return (value ?? 0).toLocaleString('en-US');
};

export const totalRarities = (r) =>
    RARITY_KEYS.reduce((a, k) => a + (r?.[RARITY_FIELDS[k]] ?? 0), 0);

// ── Small numeric helpers ────────────────────────────────────────────────────

export const winRate = (won, played) => (played > 0 ? (won / played) * 100 : 0);
export const itemsPerGame = (items, games) => (games > 0 ? items / games : 0);
export const secondsPerItem = (time, items) => (items > 0 ? time / items : 0);

export const timeAgo = (value) => {
    const then = new Date(value).getTime();
    const secs = Math.max(0, Math.floor((Date.now() - then) / 1000));
    if (secs < 60) return 'just now';
    const mins = Math.floor(secs / 60);
    if (mins < 60) return `${mins}m ago`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h ago`;
    const days = Math.floor(hrs / 24);
    if (days < 7) return `${days}d ago`;
    const weeks = Math.floor(days / 7);
    if (weeks < 5) return `${weeks}w ago`;
    const months = Math.floor(days / 30);
    if (months < 12) return `${months}mo ago`;
    return `${Math.floor(days / 365)}y ago`;
};
