/**
 * GENERATED by scripts/vendor-pool.mjs from this repo's config.yml. Do not edit by hand.
 *
 * INFO: what /info prints for each item a Commands example asks about, line for line,
 *   with the & colour codes the game reads.
 */

export const INFO = {
  "SNIFFER_EGG": [
    "&b&lSniffer Egg &7| &6Item Information",
    "&7",
    "&7Structure: &aWarm Ocean Ruins",
    "&7Biomes: &aWarm&7, &aLukewarm Ocean&7, &aDeep Lukewarm Ocean",
    "&7Tool: &aBrush",
    "&7Brush &asuspicious sand &7to obtain the item",
    "&7Chance: &66.7%"
  ]
};
