/**
 * GENERATED by scripts/vendor-pool.mjs — do not edit by hand.
 *
 * The display name a material answers to when one of the plugin's custom items owns it
 * (6 of them), mirroring CustomMaterials.nameOf(). NETHER_STAR is the Wheel of
 * Fortune, KNOWLEDGE_BOOK the Antimatter Locator, and so on: these materials are never
 * handed out as themselves, so calling them by their vanilla name is simply wrong.
 *
 * Materials in the plugin's SHARES_MATERIAL_WITH_POOL_ITEM set are deliberately absent —
 * BRUSH is a real EARLY force item that merely shares its material with the Kiln-Fired
 * Brush, and TOTEM_OF_UNDYING with the Totem of Antimatter, so both keep vanilla names.
 *
 * Keys are bare Material enums; look up with an upper-cased key.
 */

export const CUSTOM_ITEM_NAMES = {
  KNOWLEDGE_BOOK: "Antimatter Locator",
  MUSIC_DISC_CHIRP: "Sulfur Locator",
  NETHER_STAR: "Wheel of Fortune",
  TORCHFLOWER: "Weathered Captain's Journal",
  TORCHFLOWER_SEEDS: "Eye of Antimatter",
  WITHER_ROSE: "Trial Locator",
};
