/**
 * Vendors the FIB item pool into `src/pages/Stats/itemPool.js`.
 *
 * The stats collection book shows the WHOLE pool — found items lit, missing
 * ones dimmed — so it needs the complete list of items the game can ask for.
 * No endpoint returns it: `/items` is only the rarity snapshot of items that
 * have already come up in matches, and `/collection/{player}` carries the pool
 * SIZE (totalItems) but not its names.
 *
 * The authoritative source is the plugin itself: every
 * `register(Material.X, State.Y, ...)` call in ItemDifficultiesManager.java is
 * a pool item, minus the tag classes the live config disables. The deployed
 * config (config.yml, repo root) has `extreme: false`, which removes exactly
 * the 50 EXTREME-tagged items: 1,367 registered - 50 = the 1,317 the service
 * reports as totalItems. The same filter is applied here from the same file,
 * so a config change re-filters on the next run.
 *
 *   node scripts/vendor-pool.mjs
 */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/* The same URL the item-pools page parses at runtime. */
const JAVA_URL =
  'https://raw.githubusercontent.com/McPlayHDnet/ForceItemBattle/main/src/main/java/forceitembattle/manager/ItemDifficultiesManager.java';

const CONFIG = join(root, 'config.yml');
const OUT = join(root, 'src/pages/Stats/itemPool.js');
const TEXTURES = join(root, 'public/fib-items');

const REGISTER = /register\(Material\.(\w+),\s*State\.(\w+)((?:,\s*ItemTag\.\w+)*)\)/g;

/** The two-space-indented booleans under `settings:` in config.yml. */
function readSettings(yaml) {
  const get = (key, fallback) => {
    const m = yaml.match(new RegExp(`^  ${key}:\\s*(true|false)\\s*$`, 'm'));
    return m ? m[1] === 'true' : fallback;
  };
  return {
    hard: get('hard', false),
    extreme: get('extreme', false),
    /* Never written to config.yml: the live pool (1,317) includes the 34
       END-tagged items, so enabled is the proven default. */
    end: get('end', true),
  };
}

/** The same exclusions ItemDifficultiesManager.filterDisabledItems applies. */
function poolFilter(settings) {
  return (tags) => {
    if (!settings.hard && (tags.includes('NETHER') || tags.includes('EXTREME'))) return false;
    if (settings.hard && !settings.extreme && tags.includes('EXTREME')) return false;
    if (!settings.end && tags.includes('END')) return false;
    return true;
  };
}

async function main() {
  const [javaRes, yaml] = await Promise.all([
    fetch(JAVA_URL),
    readFile(CONFIG, 'utf8'),
  ]);
  if (!javaRes.ok) {
    console.error(`Could not fetch ${JAVA_URL} (HTTP ${javaRes.status}).`);
    process.exit(1);
  }
  const java = await javaRes.text();
  const settings = readSettings(yaml);
  const keep = poolFilter(settings);

  const registered = [];
  const kept = new Map(); // material -> State (EARLY/MID/LATE, the match phase it unlocks in)
  for (const m of java.matchAll(REGISTER)) {
    const material = m[1];
    const state = m[2];
    const tags = (m[3].match(/ItemTag\.(\w+)/g) ?? []).map((t) => t.slice(8));
    registered.push(material);
    if (keep(tags)) kept.set(material, state);
  }
  if (registered.length === 0) {
    console.error('Parsed zero register() calls — the manager source format has changed.');
    process.exit(1);
  }
  const pool = [...kept.keys()].sort();

  const header = `/**
 * GENERATED by scripts/vendor-pool.mjs — do not edit by hand.
 *
 * The full FIB item pool: every item the game can ask for, parsed from the
 * register() calls in the plugin's ItemDifficultiesManager.java with the live
 * config.yml exclusions applied (hard: ${settings.hard}, extreme: ${settings.extreme}, end: ${settings.end}
 * -> ${registered.length} registered, ${pool.length} in the pool). Re-run
 *   npm run vendor:pool
 * when the pool or the config changes.
 *
 * Names are bare Material enums (ACACIA_BOAT). Endpoint itemNames arrive
 * namespaced and lowercase (minecraft:acacia_boat); join the two with
 * itemKey(), which strips the namespace and case-folds.
 *
 * ITEM_STATE carries each item's match phase (EARLY/MID/LATE — when in a
 * match it can start coming up), straight from the same register() calls.
 */
`;

  const body =
    `export const ITEM_POOL = [\n${pool.map((n) => `  '${n}',`).join('\n')}\n];\n\n` +
    `export const ITEM_STATE = {\n${pool.map((n) => `  ${n}: '${kept.get(n)}',`).join('\n')}\n};\n`;
  await writeFile(OUT, header + '\n' + body);

  /* Texture coverage, so a pool addition that outruns vendor-textures is loud
     here rather than a slow remote fallback in the browser. */
  let textures = [];
  try {
    textures = await readdir(TEXTURES);
  } catch { /* no vendored set yet; vendor-textures will create it */ }
  const have = new Set(textures.filter((f) => f.endsWith('.png')).map((f) => f.slice(0, -4)));
  const untextured = pool.filter((n) => !have.has(n.toLowerCase()));

  const phases = pool.reduce((acc, n) => {
    const s = kept.get(n);
    acc[s] = (acc[s] ?? 0) + 1;
    return acc;
  }, {});
  console.log(
    `Wrote ${pool.length} pool items -> src/pages/Stats/itemPool.js ` +
    `(${registered.length} registered, settings hard=${settings.hard} extreme=${settings.extreme} end=${settings.end}; ` +
    `phases ${Object.entries(phases).map(([s, n]) => `${s} ${n}`).join('/')})`,
  );
  if (untextured.length) {
    console.warn(
      `${untextured.length} pool item(s) have no vendored texture — re-run npm run vendor:textures: ` +
      untextured.join(', '),
    );
  }
}

main();
